version: "3.9"

services:
    db:
        image: postgres:16.2
        # set shared memory limit when using docker-compose
        shm_size: 128mb
        environment:
            POSTGRES_PASSWORD: 123456
            POSTGRES_USER: hiro
            POSTGRES_DB: vcs-msm
        entrypoint: /docker-entrypoint-initdb.d 
    cache:
        image: redis:7.2
    kafka:
        image: bitnami/kafka:3.7.0
        environment:
            - KAFKA_CFG_NODE_ID=0
            - KAFKA_CFG_PROCESS_ROLES=controller,broker
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
